name: Production Deployment
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: "iam.googleapis.com/projects/974955743366/locations/global/workloadIdentityPools/faryne-api-workload-identity/providers/github"
          service_account: "nou-python@faryne.iam.gserviceaccount.com"
      - uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          tags:
            - 'faryne/nou-python:latest'
            - 'faryne/nou-python:${{ github.sha }}'
      - uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: "nou-python"
          image: "faryne/nou-python:${{ github.sha }}"
